version: '3.1'
networks:
  neon-core:
volumes:
  xdg:
    driver_opts:
      type: xdg
      o: bind
      device: ${NEON_XDG_PATH}
services:
  neon-messagebus:
    container_name: neon-messagebus
    image: ghcr.io/neongeckocom/neon_messagebus:dev
    ports:
    - "8181:8181"
    networks:
      neon-core:
        aliases:
        - messagebus
    volumes:
    - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - XDG_CONFIG_HOME=${XDG_RUNTIME_DIR}/config
    - XDG_DATA_HOME=${XDG_RUNTIME_DIR}/data
    - XDG_CACHE_HOME=${XDG_RUNTIME_DIR}/cache
    - XDG_STATE_HOME=${XDG_RUNTIME_DIR}/state
  neon-skills:
    container_name: neon-skills
    image: ghcr.io/neongeckocom/neon_skills-default_skills:dev
    networks:
    - neon-core
    volumes:
    - ~/.config/pulse/cookie:/tmp/pulse_cookie:ro
    - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    - ${NEON_SKILLS_DIR}:/skills:ro
    - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - PULSE_COOKIE=/tmp/pulse_cookie
    - XDG_CONFIG_HOME=${XDG_RUNTIME_DIR}/config
    - XDG_DATA_HOME=${XDG_RUNTIME_DIR}/data
    - XDG_CACHE_HOME=${XDG_RUNTIME_DIR}/cache
    - XDG_STATE_HOME=${XDG_RUNTIME_DIR}/state